"""
<Entity Name> Domain Entity

AI-CONTEXT: Hexagonal Architecture - Domain Layer
AI-CONTEXT: Represents <what this entity represents>
AI-CONTEXT: Pure business logic, NO external dependencies
AI-CONTEXT: NO I/O operations, NO framework dependencies

Created: <YYYY-MM-DD>
Last updated: <YYYY-MM-DD> (<what changed>)
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List, Dict, Any
from enum import Enum

# AI-CRITICAL: Core domain entity
# Changes here affect entire project - handle with care
# AI-LINK: core/usecases/<related_usecase>.py (business logic)
# AI-LINK: adapters/storage/<storage>.py (persistence)

# AI-HINT: Use Enum for status/type fields
class MyEntityStatus(Enum):
    """
    Status values for MyEntity
    
    AI-HINT: Add new statuses at the end to maintain compatibility
    """
    STATUS_ONE = "status_one"
    STATUS_TWO = "status_two"

# AI-WARNING: Don't change field types without migration!
# AI-WARNING: Changing structure requires bot_configs.json migration
@dataclass
class MyEntity:
    """
    <Entity description>
    
    Attributes:
        field1: <description>
        field2: <description>
        
    AI-USAGE:
        - Created in: <where entities are created>
        - Used in: <where it's used>
        - Persisted by: adapters/storage/<storage>.py
        
    AI-LINK: core/usecases/<usecase>.py:<method>() (creation)
    AI-LINK: adapters/storage/<storage>.py (persistence)
    """
    
    # AI-HINT: Required fields first
    id: int  # AI-HINT: Unique identifier, generated by system
    name: str
    status: MyEntityStatus
    
    # AI-HINT: Optional fields with defaults
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: Optional[datetime] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # AI-CRITICAL: Important business methods
    # AI-WARNING: Don't change business rules without tests
    def can_perform_action(self) -> bool:
        """
        Check if entity can perform some action
        
        Returns:
            bool: True if action allowed
            
        AI-HINT: Business rule: <describe the rule>
        AI-LINK: core/usecases/<usecase>.py:<method>() (uses this check)
        """
        return self.status == MyEntityStatus.STATUS_ONE
    
    def perform_action(self) -> None:
        """
        Perform important action
        
        AI-WARNING: Must check can_perform_action() first!
        AI-HINT: This changes entity state
        """
        if not self.can_perform_action():
            raise ValueError(f"Cannot perform action in status {self.status}")
        
        # AI-HINT: Update state
        self.status = MyEntityStatus.STATUS_TWO
        self.updated_at = datetime.now()
    
    # AI-HINT: Serialization for storage
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for storage
        
        Returns:
            Dict with all entity data
            
        AI-LINK: adapters/storage/<storage>.py (uses this)
        AI-HINT: Used by JSON storage adapter
        """
        return {
            "id": self.id,
            "name": self.name,
            "status": self.status.value,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "metadata": self.metadata,
        }
    
    # AI-HINT: Deserialization from storage
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'MyEntity':
        """
        Create entity from dictionary
        
        Args:
            data: Dictionary with entity data
            
        Returns:
            MyEntity instance
            
        AI-LINK: adapters/storage/<storage>.py (uses this)
        AI-WARNING: Must handle missing fields gracefully for backward compatibility
        """
        return cls(
            id=data["id"],
            name=data["name"],
            status=MyEntityStatus(data["status"]),
            created_at=datetime.fromisoformat(data["created_at"]) if data.get("created_at") else datetime.now(),
            updated_at=datetime.fromisoformat(data["updated_at"]) if data.get("updated_at") else None,
            metadata=data.get("metadata", {}),
        )
    
    # AI-HINT: Validation
    def validate(self) -> List[str]:
        """
        Validate entity state
        
        Returns:
            List of validation errors (empty if valid)
            
        AI-HINT: Call before saving to storage
        AI-LINK: core/usecases/<usecase>.py (validates before save)
        """
        errors = []
        
        if not self.name:
            errors.append("Name is required")
        if len(self.name) > 255:
            errors.append("Name too long (max 255)")
            
        return errors

# AI-HINT: Usage example in doctest or comments
# AI-HINT: More documentation in docs/CONTEXT.md "Data Models" section
# AI-TODO: <Future improvements if any>

