"""Add logic fields retry 2

Revision ID: a3da71ecffdf
Revises: bd3a4796ba8b
Create Date: 2025-11-23 07:53:01.740211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3da71ecffdf'
down_revision: Union[str, None] = 'bd3a4796ba8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add nullable columns
    op.add_column('bots', sa.Column('system_prompt', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('voice_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bots', sa.Column('assistant_id', sa.String(), nullable=True))

    # 2. Populate existing rows
    op.execute("UPDATE bots SET system_prompt = 'You are a helpful assistant.' WHERE system_prompt IS NULL")
    op.execute("UPDATE bots SET voice_settings = '{\"voice_id\": \"alloy\", \"speed\": 1.0}'::jsonb WHERE voice_settings IS NULL")

    # 3. Make columns not null
    op.alter_column('bots', 'system_prompt', nullable=False)
    op.alter_column('bots', 'voice_settings', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'assistant_id')
    op.drop_column('bots', 'voice_settings')
    op.drop_column('bots', 'system_prompt')
    # ### end Alembic commands ###
