"""Add thread_id to conversations

Revision ID: c69ed623610a
Revises: a3da71ecffdf
Create Date: 2025-11-23 07:56:57.035636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69ed623610a'
down_revision: Union[str, None] = 'a3da71ecffdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('thread_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_column('conversations', 'thread_id')
    # ### end Alembic commands ###
